FROM python:3.11

WORKDIR /app-streamlit

COPY . /app-streamlit
# COPY requirements-streamlit.txt /app-streamlit

RUN pip install --upgrade pip
RUN pip install -r /app-streamlit/requirements-streamlit.txt

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]