FROM python:3.11

WORKDIR /app-api

COPY . /app-api

RUN pip install --upgrade pip
RUN pip install -r /app-api/requirements-api.txt

# Exponha a porta 8000
EXPOSE 8000

CMD ["uvicorn", "main:vApp", "--host", "0.0.0.0", "--port", "8000"]